# =============================================================================
# Malware Sandbox Infrastructure — Makefile
# Single entry point for the full build/deploy pipeline.
#
# Usage:
#   make image       — build Packer base image
#   make infra       — provision infrastructure with Terraform
#   make configure   — configure host with Ansible
#   make all         — image + infra + configure
#
# Author: Christopher Shaiman
# License: Apache 2.0
# =============================================================================

.PHONY: all image infra-ovh infra-aws lambda configure validate clean configure-backend help

# -----------------------------------------------------------------------------
# Configuration — override via environment or .env file
# -----------------------------------------------------------------------------

AWS_ENV         ?= prod
ANSIBLE_USER    ?= root
PACKER_DIR      := packer
ANSIBLE_DIR     := ansible
OVH_DIR         := ovh
AWS_DIR         := aws/envs/$(AWS_ENV)

# Load .env if it exists (local secrets, not committed)
-include .env

# -----------------------------------------------------------------------------
# Help
# -----------------------------------------------------------------------------

help:
	@echo ""
	@echo "Malware Sandbox Infrastructure"
	@echo "================================"
	@echo ""
	@echo "  make configure-backend  Populate shared/backend-aws.hcl from bootstrap outputs"
	@echo "  make lambda             Zip Lambda handler source into src/*.zip"
	@echo "  make image              Build Packer base image"
	@echo "  make infra-ovh          Provision OVH bare metal"
	@echo "  make infra-aws          Provision AWS supporting infra (run make lambda first)"
	@echo "  make configure          Run Ansible against provisioned host"
	@echo "  make all                Full pipeline: lambda + image + infra + configure"
	@echo "  make validate           Validate Packer + Terraform configs"
	@echo "  make clean              Remove local build artifacts"
	@echo ""
	@echo "  First-time setup order:"
	@echo "    1. cd aws/bootstrap && terraform init && terraform apply"
	@echo "    2. make configure-backend"
	@echo "    3. make lambda && make infra-aws"
	@echo "    4. make image && make infra-ovh && make configure"
	@echo ""
	@echo "  AWS_ENV=prod            AWS environment (prod | staging)"
	@echo ""

# -----------------------------------------------------------------------------
# Full pipeline
# -----------------------------------------------------------------------------

all: lambda image infra-ovh infra-aws configure

# -----------------------------------------------------------------------------
# configure-backend — populate shared/backend-aws.hcl from bootstrap outputs
# Run once after: cd aws/bootstrap && terraform init && terraform apply
# Re-run if you recreate the bootstrap bucket or change the name_prefix.
# -----------------------------------------------------------------------------

configure-backend:
	@echo "==> Populating shared/backend-aws.hcl from bootstrap outputs..."
	@[ -f aws/bootstrap/.terraform/terraform.tfstate ] || \
		(echo "ERROR: Bootstrap not initialised. Run: cd aws/bootstrap && terraform init && terraform apply" && exit 1)
	@cd aws/bootstrap && \
		BUCKET=$$(terraform output -raw tfstate_bucket_name) && \
		TABLE=$$(terraform output -raw tfstate_lock_table) && \
		REGION=$$(terraform output -raw aws_region) && \
		printf '# shared/backend-aws.hcl — generated by make configure-backend\n# Re-run this target if the bootstrap bucket or table name changes.\nbucket         = "%s"\nkey            = "prod/aws/terraform.tfstate"\nregion         = "%s"\nencrypt        = true\ndynamodb_table = "%s"\n' \
			"$$BUCKET" "$$REGION" "$$TABLE" > ../../shared/backend-aws.hcl
	@echo "==> shared/backend-aws.hcl updated. Run: make infra-aws"

# -----------------------------------------------------------------------------
# Lambda — zip handler source for terraform apply
# Zips are checked into .gitignore and rebuilt from src/ before each apply.
# terraform apply references src/report_processor.zip and src/sample_submitter.zip
# (set via report_processor_zip / sample_submitter_zip in terraform.tfvars).
# -----------------------------------------------------------------------------

lambda:
	@echo "==> Building Lambda deployment packages..."
	@cd src && zip -q report_processor.zip report_processor.py
	@cd src && zip -q sample_submitter.zip sample_submitter.py
	@echo "==> Lambda packages built: src/report_processor.zip src/sample_submitter.zip"

# -----------------------------------------------------------------------------
# Packer — build hardened base image
# Outputs qcow2 to packer/output/ then uploads snapshot to OVH
# -----------------------------------------------------------------------------

image:
	@echo "==> Building Packer base image..."
	@cd $(PACKER_DIR) && \
		packer init . && \
		packer validate . && \
		packer build ubuntu-sandbox.pkr.hcl
	@echo "==> Image build complete."

# -----------------------------------------------------------------------------
# Terraform — OVH bare metal
# -----------------------------------------------------------------------------

infra-ovh:
	@echo "==> Provisioning OVH infrastructure..."
	@[ -f $(OVH_DIR)/terraform.tfvars ] || \
		(echo "ERROR: $(OVH_DIR)/terraform.tfvars not found. Copy terraform.tfvars.example and fill in values." && exit 1)
	@cd $(OVH_DIR) && \
		terraform init \
			-backend-config="../shared/backend-aws.hcl" && \
		terraform plan \
			-out=tfplan && \
		terraform apply tfplan
	@echo "==> OVH provisioning complete."
	@echo "==> Writing Ansible inventory..."
	@cd $(OVH_DIR) && \
		terraform output -raw sandbox_public_ip > ../ansible/inventory/hosts

infra-aws:
	@echo "==> Provisioning AWS infrastructure..."
	@[ -f $(AWS_DIR)/terraform.tfvars ] || \
		(echo "ERROR: $(AWS_DIR)/terraform.tfvars not found." && exit 1)
	@cd $(AWS_DIR) && \
		terraform init \
			-backend-config="../../shared/backend-aws.hcl" && \
		terraform plan \
			-out=tfplan && \
		terraform apply tfplan
	@echo "==> AWS provisioning complete."

# -----------------------------------------------------------------------------
# Ansible — configure the host
# Runs after Terraform writes the inventory file
# -----------------------------------------------------------------------------

configure:
	@echo "==> Configuring host with Ansible..."
	@[ -f $(ANSIBLE_DIR)/inventory/hosts ] || \
		(echo "ERROR: ansible/inventory/hosts not found. Run make infra-ovh first." && exit 1)
	@cd $(ANSIBLE_DIR) && \
		ansible-playbook \
			-i inventory/hosts \
			-u $(ANSIBLE_USER) \
			--private-key ~/.ssh/sandbox_ed25519 \
			site.yml
	@echo "==> Configuration complete."

# -----------------------------------------------------------------------------
# Validation — run before committing
# -----------------------------------------------------------------------------

validate:
	@echo "==> Validating Packer..."
	@cd $(PACKER_DIR) && packer init . && packer validate .
	@echo "==> Validating OVH Terraform..."
	@cd $(OVH_DIR) && terraform init -backend=false && terraform validate
	@echo "==> Validating AWS Terraform modules..."
	@for dir in aws/modules/*/; do \
		echo "  Validating $$dir..."; \
		cd $$dir && terraform init -backend=false && terraform validate && cd ../../..; \
	done
	@echo "==> Validating Ansible..."
	@cd $(ANSIBLE_DIR) && ansible-playbook --syntax-check -i inventory/hosts site.yml
	@echo "==> All validation passed."

# -----------------------------------------------------------------------------
# Clean
# -----------------------------------------------------------------------------

clean:
	@echo "==> Cleaning build artifacts..."
	@rm -rf $(PACKER_DIR)/output/
	@rm -f src/report_processor.zip src/sample_submitter.zip
	@find . -name "tfplan" -delete
	@find . -name ".terraform" -type d -exec rm -rf {} + 2>/dev/null || true
	@find . -name "*.tfstate.backup" -delete
	@echo "==> Clean complete."
