# =============================================================================
# Malware Sandbox Infrastructure — Makefile
# Single entry point for the full build/deploy pipeline.
#
# Usage:
#   make image       — build Packer base image
#   make infra       — provision infrastructure with Terraform
#   make configure   — configure host with Ansible
#   make all         — image + infra + configure
#
# Author: Christopher Shaiman
# License: Apache 2.0
# =============================================================================

.PHONY: all image win11-image autounattend-floppy infra-ovh infra-aws lambda configure validate clean configure-backend packer-setup help

# -----------------------------------------------------------------------------
# Configuration — override via environment or .env file
# -----------------------------------------------------------------------------

AWS_ENV         ?= prod
ANSIBLE_USER    ?= root
PACKER_DIR      := packer
ANSIBLE_DIR     := ansible
OVH_DIR         := ovh
AWS_DIR         := aws/envs/$(AWS_ENV)

# OVMF firmware vars template — must match ovmf_vars default in windows11-guest.pkr.hcl.
# Empty VARS (not .ms.fd): no pre-built PXE/HTTP boot entries, OVMF drops to
# UEFI shell so boot_command can type the ISO path. Override in .env if needed.
OVMF_VARS_TEMPLATE ?= /usr/share/OVMF/OVMF_VARS_4M.fd
# Path for the writable OVMF VARS file — must be OUTSIDE the packer output directory.
# packer -force deletes the output directory before QEMU starts; keeping efivars.fd
# here ensures it survives that cleanup. Must match efivars_path in windows11-guest.pkr.hcl.
EFIVARS_PATH       ?= /tmp/packer-win11-efivars.fd

# Load .env if it exists (local secrets, not committed)
-include .env

# -----------------------------------------------------------------------------
# Help
# -----------------------------------------------------------------------------

help:
	@echo ""
	@echo "Malware Sandbox Infrastructure"
	@echo "================================"
	@echo ""
	@echo "  make packer-setup         One-time: generate build password + install Ansible hardening role"
	@echo "  make configure-backend    Populate shared/backend-aws.hcl from bootstrap outputs"
	@echo "  make lambda               Zip Lambda handler source into src/*.zip"
	@echo "  make autounattend-floppy  Create autounattend floppy image for Windows 11 builds (run once per XML change)"
	@echo "  make win11-image          Build Windows 11 guest image (runs autounattend-floppy first)"
	@echo "  make image                Build Ubuntu sandbox base image"
	@echo "  make infra-ovh            Provision OVH bare metal"
	@echo "  make infra-aws            Provision AWS supporting infra (run make lambda first)"
	@echo "  make configure            Run Ansible against provisioned host"
	@echo "  make all                  Full pipeline: lambda + image + infra + configure"
	@echo "  make validate             Validate Packer + Terraform configs"
	@echo "  make clean                Remove local build artifacts"
	@echo ""
	@echo "  First-time setup order:"
	@echo "    1. cd aws/bootstrap && terraform init && terraform apply"
	@echo "    2. make configure-backend"
	@echo "    3. make lambda && make infra-aws"
	@echo "    4. make autounattend-floppy && make win11-image && make infra-ovh && make configure"
	@echo ""
	@echo "  AWS_ENV=prod              AWS environment (prod | staging)"
	@echo ""

# -----------------------------------------------------------------------------
# Full pipeline
# -----------------------------------------------------------------------------

all: lambda image infra-ovh infra-aws configure

# -----------------------------------------------------------------------------
# configure-backend — populate shared/backend-aws.hcl from bootstrap outputs
# Run once after: cd aws/bootstrap && terraform init && terraform apply
# Re-run if you recreate the bootstrap bucket or change the name_prefix.
# -----------------------------------------------------------------------------

configure-backend:
	@echo "==> Populating shared/backend-aws.hcl from bootstrap outputs..."
	@[ -f aws/bootstrap/terraform.tfstate ] || \
		(echo "ERROR: Bootstrap not applied. Run: cd aws/bootstrap && terraform init && terraform apply" && exit 1)
	@cd aws/bootstrap && \
		BUCKET=$$(terraform output -raw tfstate_bucket_name) && \
		TABLE=$$(terraform output -raw tfstate_lock_table) && \
		REGION=$$(terraform output -raw aws_region) && \
		printf '# shared/backend-aws.hcl — generated by make configure-backend\n# Re-run this target if the bootstrap bucket or table name changes.\nbucket         = "%s"\nkey            = "prod/aws/terraform.tfstate"\nregion         = "%s"\nencrypt        = true\ndynamodb_table = "%s"\n' \
			"$$BUCKET" "$$REGION" "$$TABLE" > ../../shared/backend-aws.hcl
	@echo "==> shared/backend-aws.hcl updated. Run: make infra-aws"

# -----------------------------------------------------------------------------
# Lambda — zip handler source for terraform apply
# Zips are checked into .gitignore and rebuilt from src/ before each apply.
# terraform apply references src/report_processor.zip and src/sample_submitter.zip
# (set via report_processor_zip / sample_submitter_zip in terraform.tfvars).
# -----------------------------------------------------------------------------

lambda:
	@echo "==> Building Lambda deployment packages..."
	@cd src && zip -q report_processor.zip report_processor.py
	@cd src && zip -q sample_submitter.zip sample_submitter.py
	@echo "==> Lambda packages built: src/report_processor.zip src/sample_submitter.zip"

# -----------------------------------------------------------------------------
# packer-setup — one-time setup before first packer build
# Generates the build password hash and installs the Ansible hardening role.
# Run this once, then follow the printed instructions.
# -----------------------------------------------------------------------------

packer-setup:
	@echo "==> Installing konstruktoid.hardening Ansible role..."
	@ansible-galaxy install konstruktoid.hardening -p $(PACKER_DIR)/ansible/roles
	@echo ""
	@echo "==> Generating build password hash..."
	@echo "    Enter a password for the Packer build user (used only during image build):"
	@read -s PW && \
		HASH=$$(openssl passwd -6 "$$PW") && \
		echo "" && \
		echo "  1. Replace the placeholder in packer/http/user-data identity.password with:" && \
		echo "     $$HASH" && \
		echo "" && \
		echo "  2. Create packer/packer.auto.pkrvars.hcl with:" && \
		echo '     ssh_password = "'$$PW'"'
	@echo ""
	@echo "==> packer-setup complete. Update user-data and pkrvars, then run: make image"

# -----------------------------------------------------------------------------
# autounattend-floppy — create a 1.44 MB FAT12 floppy image with autounattend.xml
# at the root. WinPE checks A: before all other drives — reliable regardless of ISO
# filesystem type. Run once; re-run whenever answer-files/win11-autounattend.xml changes.
# Requires mtools (apt-get install mtools).
# Override the output path with: make autounattend-floppy AUTOUNATTEND_IMG=/your/path
# The path must match autounattend_img_path in packer.auto.pkrvars.hcl.
# -----------------------------------------------------------------------------

AUTOUNATTEND_IMG ?= $(PACKER_DIR)/output/autounattend.img

autounattend-floppy:
	@echo "==> Creating autounattend floppy image at $(AUTOUNATTEND_IMG)..."
	@command -v mformat >/dev/null 2>&1 || \
		(echo "ERROR: mtools not found. Run: sudo apt-get install mtools" && exit 1)
	@mkdir -p $(dir $(AUTOUNATTEND_IMG))
	@dd if=/dev/zero of=$(AUTOUNATTEND_IMG) bs=512 count=2880 2>/dev/null
	@mformat -i $(AUTOUNATTEND_IMG) -f 1440 ::
	@mcopy -i $(AUTOUNATTEND_IMG) \
		$(PACKER_DIR)/answer-files/win11-autounattend.xml \
		::/autounattend.xml
	@mcopy -i $(AUTOUNATTEND_IMG) \
		$(PACKER_DIR)/answer-files/startup.nsh \
		::/startup.nsh
	@echo "==> $(AUTOUNATTEND_IMG) ready."

# -----------------------------------------------------------------------------
# win11-image — build Windows 11 guest image
# Runs autounattend-floppy first to ensure the floppy is current.
# Build is fully unattended — WinPE finds A:\autounattend.xml automatically.
# Expect 45-90 minutes. Run inside tmux/screen.
#
# Boot flow: OVMF drops to UEFI shell (USB not ready in nested KVM) →
# boot-helper.sh types FS0:\EFI\BOOT\bootx64.efi via QEMU monitor sendkey →
# WinPE boots, finds autounattend.xml on A: → unattended install → WinRM up.
# -----------------------------------------------------------------------------

win11-image: autounattend-floppy
	@echo "==> Building Windows 11 guest image..."
	@[ -f $(PACKER_DIR)/packer.auto.pkrvars.hcl ] || \
		(echo "ERROR: packer/packer.auto.pkrvars.hcl not found." && exit 1)
	@[ -f $(OVMF_VARS_TEMPLATE) ] || \
		(echo "ERROR: OVMF VARS not found at $(OVMF_VARS_TEMPLATE). Run: sudo apt-get install ovmf" && exit 1)
	@command -v socat >/dev/null 2>&1 || \
		(echo "ERROR: socat not found. Run: sudo apt-get install socat" && exit 1)
	@[ -n "$(QEMU_MONITOR_SOCK)" ] || \
		(echo "ERROR: QEMU_MONITOR_SOCK not set. Add it to .env (must match -monitor path in HCL qemuargs)." && exit 1)
	@echo "==> Copying fresh OVMF VARS to $(EFIVARS_PATH) (clears stale NVRAM boot entries)..."
	@cp $(OVMF_VARS_TEMPLATE) $(EFIVARS_PATH)
	@echo "==> Starting boot helper (sends keystrokes via QEMU monitor at $(QEMU_MONITOR_SOCK))..."
	@chmod +x $(PACKER_DIR)/scripts/boot-helper.sh
	@[ -n "$(WIN11_ISO_PATH)" ] || \
		(echo "ERROR: WIN11_ISO_PATH not set. Add it to .env (must match win11_iso_path in pkrvars)." && exit 1)
	@[ -n "$(WIN11_OUTPUT_DIR)" ] || \
		(echo "ERROR: WIN11_OUTPUT_DIR not set. Add it to .env (must match output_directory in pkrvars)." && exit 1)
	@$(PACKER_DIR)/scripts/boot-helper.sh $(QEMU_MONITOR_SOCK) $(WIN11_ISO_PATH) $(WIN11_OUTPUT_DIR) &
	@cd $(PACKER_DIR) && \
		packer init windows11-guest.pkr.hcl && \
		packer build -force -var-file=packer.auto.pkrvars.hcl windows11-guest.pkr.hcl
	@echo "==> Windows 11 guest image complete. Output: check output_directory in packer.auto.pkrvars.hcl"

# -----------------------------------------------------------------------------
# Packer — build hardened base image
# Outputs qcow2 to packer/output/ then uploads snapshot to OVH via BYOI API.
# Run make packer-setup first if this is your first build.
# -----------------------------------------------------------------------------

image:
	@echo "==> Checking packer-setup prerequisites..."
	@grep -q "PLACEHOLDER" $(PACKER_DIR)/http/user-data && \
		(echo "ERROR: packer/http/user-data still has placeholder password hash. Run: make packer-setup" && exit 1) || true
	@[ -f $(PACKER_DIR)/packer.auto.pkrvars.hcl ] || \
		(echo "ERROR: packer/packer.auto.pkrvars.hcl not found. Run: make packer-setup" && exit 1)
	@echo "==> Building Packer base image..."
	@cd $(PACKER_DIR) && \
		packer init . && \
		packer validate . && \
		packer build ubuntu-sandbox.pkr.hcl
	@echo "==> Image build complete: packer/output/ubuntu-sandbox.qcow2"
	@echo "==> Next: upload to S3 and deploy via OVH BYOI API"

# -----------------------------------------------------------------------------
# Terraform — OVH bare metal
# -----------------------------------------------------------------------------

infra-ovh:
	@echo "==> Provisioning OVH infrastructure..."
	@[ -f $(OVH_DIR)/terraform.tfvars ] || \
		(echo "ERROR: $(OVH_DIR)/terraform.tfvars not found. Copy terraform.tfvars.example and fill in values." && exit 1)
	@cd $(OVH_DIR) && \
		terraform init \
			-backend-config="../shared/backend-aws.hcl" && \
		terraform plan \
			-out=tfplan && \
		terraform apply tfplan
	@echo "==> OVH provisioning complete."
	@echo "==> Writing Ansible inventory..."
	@cd $(OVH_DIR) && \
		terraform output -raw sandbox_public_ip > ../ansible/inventory/hosts

infra-aws:
	@echo "==> Provisioning AWS infrastructure..."
	@[ -f $(AWS_DIR)/terraform.tfvars ] || \
		(echo "ERROR: $(AWS_DIR)/terraform.tfvars not found." && exit 1)
	@cd $(AWS_DIR) && \
		terraform init \
			-backend-config="../../shared/backend-aws.hcl" && \
		terraform plan \
			-out=tfplan && \
		terraform apply tfplan
	@echo "==> AWS provisioning complete."

# -----------------------------------------------------------------------------
# Ansible — configure the host
# Runs after Terraform writes the inventory file
# -----------------------------------------------------------------------------

configure:
	@echo "==> Configuring host with Ansible..."
	@[ -f $(ANSIBLE_DIR)/inventory/hosts ] || \
		(echo "ERROR: ansible/inventory/hosts not found. Run make infra-ovh first." && exit 1)
	@echo "==> Installing Ansible Galaxy requirements..."
	@ansible-galaxy install -r $(ANSIBLE_DIR)/requirements.yml --force-with-deps
	@cd $(ANSIBLE_DIR) && \
		ansible-playbook \
			-i inventory/hosts \
			-u $(ANSIBLE_USER) \
			--private-key ~/.ssh/sandbox_ed25519 \
			site.yml
	@echo "==> Configuration complete."

# -----------------------------------------------------------------------------
# Validation — run before committing
# -----------------------------------------------------------------------------

validate:
	@echo "==> Validating Packer..."
	@cd $(PACKER_DIR) && packer init . && packer validate .
	@echo "==> Validating OVH Terraform..."
	@cd $(OVH_DIR) && terraform init -backend=false && terraform validate
	@echo "==> Validating AWS Terraform modules..."
	@for dir in aws/modules/*/; do \
		echo "  Validating $$dir..."; \
		cd $$dir && terraform init -backend=false && terraform validate && cd ../../..; \
	done
	@echo "==> Validating Ansible..."
	@cd $(ANSIBLE_DIR) && ansible-playbook --syntax-check -i inventory/hosts site.yml
	@echo "==> All validation passed."

# -----------------------------------------------------------------------------
# Clean
# -----------------------------------------------------------------------------

clean:
	@echo "==> Cleaning build artifacts..."
	@rm -rf $(PACKER_DIR)/output/
	@rm -f src/report_processor.zip src/sample_submitter.zip
	@find . -name "tfplan" -delete
	@find . -name ".terraform" -type d -exec rm -rf {} + 2>/dev/null || true
	@find . -name "*.tfstate.backup" -delete
	@echo "==> Clean complete."
